---
title: "R Notebook"
output: html_notebook
---

```{r "Starting chicks data and formating"}
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)

chx<-read.csv("~/Desktop/fullsummary_complete.csv")
chx<-separate(data = chx, col = d_FirstHatch, into = c("hatch_month", "hatch_day", "hatch_year"), sep = "/") 
chx$NumChicksHatched <-sub("^$", "0", chx$NumChicksHatched) 
chx$NumChicksHatched <-sub("^$", "0", chx$NumChicksHatched) 
chx$d_FirstHatch<-as.numeric(chx$d_FirstHatch, format="%m/%d/%Y")
```

```{r}

chx$hatch_day<-as.numeric(chx$hatch_day)
chx$hatch_month<-as.factor(chx$hatch_month)
chx$hatch_year<-as.factor(chx$hatch_year)
chx$NumChicksHatched<-as.numeric(chx$NumChicksHatched)

```

```{r}
library ( plyr)
levels(chx$hatch_month)[1]<-NA
range(chx$hatch_day, na.rm=TRUE)
levels(chx$hatch_month)[1]<-NA
levels(chx$hatch_year)
detach(plyr)
```

```{r "mutating the chick data frame into chicks per year"}


#aggregate(NumChicksHatched~hatch_year,chx, sum, na.action = na.omit) 
aggregate(NumChicksHatched~hatch_year,chx, length, na.action = na.omit) 

Chicks_by_year<-aggregate(NumChicksHatched~hatch_year,chx, length, na.action = na.omit) 
hatches_by_year<-aggregate(NumChicksHatched~hatch_year,chx, length, na.action = na.omit) 
```

```{r "getting chick data frame ready for graphs"}
library(ggplot2)
library(tidyverse)
library(dplyr)
chx= chx %>% mutate_if(is.factor,
                      fct_explicit_na,
                      na_level = "to_impute")
chx %>% group_by(hatch_year) %>% summarise(totalchicks = sum(NumChicksHatched))
chx %>% drop_na(hatch_year) %>%  drop_na(NumChicksHatched) %>%  group_by(hatch_year) %>% summarise(totalchicks = sum(NumChicksHatched)) 
```

```{r "Total Number of Chicks Hatched"}
C1<-ggplot(chx, aes(x=as.numeric(hatch_month), y=NumChicksHatched, color=hatch_year, shape=hatch_year))+
  geom_point()+
  ggtitle("Chicks Hatched per year") +
  labs(x="Years", y="Total Number of Chicks Hatched") +
  scale_color_discrete(name="Year") +
  
  scale_shape_discrete(name="Year")

C1 + facet_grid(cols = vars(hatch_year)) #make a grid of graphs where the columns are lay_year
C1+ facet_wrap(vars(hatch_year), ncol=2) + 
  scale_x_continuous(breaks=1:12, labels =c ("J", "F", "M", "A", "M", "J", "J", "A", "S", "O","N", "D")) +
   theme_classic()
C1
```

```{r " "}
C2<-ggplot(chx, aes(x=hatch_month, y=NumChicksHatched, fill=hatch_year))+
  geom_bar(color="black",stat = "identity",position = position_dodge(width = 0.9)) +
  ggtitle("Eggs laid per year") +
  labs(x="Months", y="Total Number of Eggs Laid") 
C2 + facet_grid(cols= vars(hatch_year)) #make a grid of graphs where the columns are lay_year
C2 + facet_wrap(vars(hatch_year), ncol=2) 
C2
```

