---
title: "Chicks"
output: html_notebook
---
```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
```

```{r "setting up weather"}
setwd("~/Desktop")
WD<-read.csv("davis_weather_2016-19_complete_cleaned.csv")
options(stringsAsFactors = FALSE)
WD$date <- as.Date(as.character(WD$date), format = "%Y%m%d")
weather_year_summary <- WD %>%
  na.omit() %>%
  mutate(month =month(date),
         year = year(date)) %>%
  group_by(year, month) %>%
  summarise(avg_precip = mean(precip),
            total_precip = sum(precip), 
            avg_high = mean(air_max), 
            ave_low = mean(air_min))
```

```{r "graphs for just weather"}
ggplot1<- ggplot(weather_year_summary, aes(x=(month), y=avg_precip, fill=as.factor(year)))+
  geom_bar(stat ="identity", position = position_dodge(0.9))+ 
  theme_classic()+
  ggtitle("Average Precipitation per Month and Year") +
  labs(x="Month", y="Average Precipitation") +
 scale_x_continuous(breaks = c(1:12), labels = c("J","F","M","A","M","J","J","A", "S", "O", "N", "D") , name= "Years")
ggplot1


ggplot(weather_year_summary, aes(x = month, y = total_precip, fill = as.factor(year))) +
  geom_bar(stat = "identity", position = position_dodge(0.9)) +
  scale_x_continuous(breaks = c(1:12), labels = c("J","F","M","A","M","J","J","A", "S", "O", "N", "D"))+ #month breaks and labels 
  labs(title = "Total Monthly Precipitation - Davis, CA",
       subtitle = "Data plotted by year",
       y = "Total precipitation (mm)",
       x = "Month") + theme_bw(base_size = 15) +
   guides(fill = guide_legend(title = "Year"))
```

```{r "reading chicks data and left join to weather"}
#chx<-read.csv("~/Desktop/fullsummary_complete.csv")
#chx$d_FirstHatch<-as.numeric(chx$d_FirstHatch, format="%m/%d/%Y")

#chx_data<-chx %>%    
 ##hatch_month = month(d_FirstHatch)) %>% 
#group_by(hatch_year, hatch_month) %>%

#summarize(total_chx = sum(as.integer(NumChicksHatched)))%>% filter(hatch_year != "2015") 


chx<-read.csv("~/Desktop/fullsummary_complete.csv") #change this back to yours :) 

chx$NumChicksHatched <-sub("^$", "0", chx$NumChicksHatched) #changes nothing to 0. 
chx$NumChicksHatched <-as.numeric(chx$NumChicksHatched) #change to numeric

#selected only columns you cared about and then filtered out the extreme chick values (like 12! makes no sense)
chx <- chx %>%
  select(d_FirstEgg, d_FirstFledge, d_FirstHatch, d_SecondHatch, NumEggsLaid, NumChicksFledged, NumChicksHatched) %>%
  filter(NumChicksHatched < 4)
  
chx$d_FirstHatch<-as.Date(chx$d_FirstHatch, format="%m/%d/%Y") #lubridate now works
chx <- chx %>%
  mutate(hatch_year = year(d_FirstHatch),
         hatch_month = month(d_FirstHatch))


aggregate(NumChicksHatched~hatch_year,chx, length, na.action = na.omit) 

Chicks_by_year<-aggregate(NumChicksHatched~hatch_year,chx, length, na.action = na.omit) 
total_chx <- chx %>% drop_na(hatch_year, NumChicksHatched)  %>% filter(between( hatch_year, 2016,2019)) %>% group_by(hatch_year, hatch_month) %>% summarise(totalchicks = sum(NumChicksHatched)) 
total_chx

```

```{r }
class(chx$NumChicksHatched)

colnames(chx)
colnames(weather_year_summary)
colnames(chx)[1:2]<-c("year", "month")

chx_weather<- left_join(chx,weather_year_summary) 
```

```{r "graph for chxs_weather"}
chxs_weather<-ggplot(chx_weather, aes(x = month, y = total_precip, fill = year)) +
  geom_bar(aes( y= total_chx, fill = year), stat = "identity", alpha= 0.5) +
  geom_line(aes(colour = year), alpha=0.5) +
  geom_point(aes(colour=year), alpha =0.5) +
  scale_x_continuous(breaks = c(1:12), labels = c("J","F","M","A","M","J","J","A", "S", "O", "N", "D")) +
  labs(title = "Total Chicks Hatched per Monthly Precipiation - Davis, CA",
       subtitle = " Bars are Total Chicks Hatched",
       y = "Average Precipitation", x = "Month") + theme_bw(base_size = 15) +
  facet_wrap(vars(year), ncol=2)
chxs_weather
```

```{r "graph for cor.tests"}
ggplot(chx_weather, aes(x = ave_low, y = total_chx)) + 
  geom_point()+ 
  geom_smooth(method = lm, color = "black")

```

```{r "cor.test aka stats for Chicks_weather"}
cor.test(chx_weather$total_chx, chx_weather$ave_low, method = "pearson")
cor.test(chx_weather$total_chx, chx_weather$avg_high, method = "pearson")
cor.test(chx_weather$total_chx, chx_weather$total_precip, method = "pearson")
cor.test(chx_weather$total_chx, chx_weather$avg_precip, method = "pearson")
```

